# ────────────────────────────────────────
# Rôle RBAC pour l'application Chuck Norris
# ────────────────────────────────────────
# Objectif : accès lecture minimale aux ressources nécessaires
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chuck-app-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list