# ────────────────────────────────────────
# ServiceAccount dédié à l'application Chuck Norris
# ────────────────────────────────────────
# Objectif : éviter l'usage du compte 'default'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chuck-app-sa
  namespace: dev