# templates/ingress.yaml

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.containerName }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appLabel }}
    stage: {{ .Values.stage }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.containerName }}-svc
                port:
                  number: 80
{{- end }}